Igalia/wpewebkit.org

- about/code.md
Namely:
- Link to the webkit.org site for WebKit sources, which is *THE* canonical place to look.
- Replace ellipsis with colon before bullet list. It was odd that this paragraph was ending with “…” if what comes right after is a list of things.
- Remove one “as well” almost immediately after another. Two paragraphs ending with the same expression next to each other didn't read great. Removed the unnecessary ellipsis as well (pun intended).
> Small fixes for the about/code.md page

- .github/workflows/deploy.yml
Add a GitHub Actions job file which gets triggered on pushes to the `master` branch, which will cause the site to be built and deployed to the live server using rsync over SSH.
The details used to connect to the server (SSH key, host, port, path) are hidden from the Actions configuration using repository secrets to avoid them being publicly visible in the repository.
> CI: Import actions to deploy to the live site

- .eleventy.js
Enabling `typographer` automatically converts double- and single-quotes into their typographic variants (`“”` and `‘’`), resulting in more polished looking output.
Disabling the `linkify` option prevents link to from being automatically generated, which solves issues like the `i.MX` string being turned into a link to `http://i.mx`. It is better to explicitly insert links using Markdown or HTML syntax when needed.
The reason to disable the `breaks` option is that otherwise line breaks generate `<br>` elements, which is not standard Markdown and results in unexpected output when source files are line-wrapped.
> 11ty: Tweak markdown-it options

- .github/workflows/pr.yml
Attach the site preview URL to the pull request description body instead of spamming the PR with new comments from the bot.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperez/ci-use-run-output/
> CI: Attach site preview URL to the pull request description

- .github/CODEOWNERS
Import a `CODEOWNERS` file, which instructs GitHub to assign default reviewers to new PRs based on which files are being changed by the PR.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperez/add-codeowners/
> CI: Add a CODEOWNERS file to auto-assign reviewers

- _includes/footer.html
- about/code.md
Mention the chat rooms (both on Matrix and Freenode), the mailing list, and Twitter.
This also removes the “Contact” box from the footer, which is now unneeded.
Fixes #21
----
Site preview: https://igalia.github.io/wpewebkit.org/aperez/add-contact/
> code: Add section with contact information

- _data/site.json
- _includes/head.html
- _includes/post.html
After the move to Eleventy, pages for releases (and others including a link in the `download` front matter data element) have been missing the download buttons.
This brings them back, by adding a `site.json` global data file to allow continue using `{% site.release_dir %}` in templates, and adapts the post template.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/dlbuttons/
> Bring back the download buttons for release pages

- .eleventy.js
- about/code.md
Replace the static cards with source package downloads with dynamically generated ones which always link to the most recent stable and unstable downloads and their release notes.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/touchup-dl-cards/
> code: Generate download cards dynamically

- package-lock.json
Resolves:
- https://npmjs.com/advisories/1523
- https://npmjs.com/advisories/1486
- https://npmjs.com/advisories/1500
This was done using the following commands, as recommended by `npm audit`, which updated the `package-lock.json` file by itself:
```sh
npm update lodash --depth 7
npm update browser-sync --depth 2
```
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-deps/
> npm: Update lodash, browser-sync to fix vulnerability

- README.md
README: Update obsoleted instructions about using jekyll
----
Site preview: https://igalia.github.io/wpewebkit.org/update-readme/
> README: Update obsoleted instructions about using jekyll

- _includes/header.html
Add one more entry in the “Documentation” drop-down menu linking to the releases schedule page.
Fixes #35
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/releases-page-link/
> Link releases schedule page from drop-down menu

- release/schedule/index.md
SSIA
----
We would want to have this merged soon because it adds WPE WebKit 2.30.x to the compatibility table, and the first stable release in the series will be done in the next weeks.
Related: it would be good to do a fix for #35 as well.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-release-compat/
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-release-compat/
> Update release compatibility table for WPE WebKit 2.30.x

- release.md
- security.md
Switch the `/release` and `/security` pages to use the `page` layout, which includes the top header, and remove the massive, now unneeded secondary header.
Fixes #34
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/fix-missing-headers/
> Make /release and /security use the "page" layout

- README.md
- package.json
Add a `serve` scriptlet. This allows running `npm run serve` and not needing to remember the Eleventy command for local development. The `README.md` file is updated accordingly.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/misc-npm-updates/
> package.json: Add "serve" scriptlet

- package-lock.json
This updates dependencies to newer compatible versions to avoid the following vulnerability:
https://www.npmjs.com/advisories/1573
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/misc-npm-updates/
> npm: Update object-path to avoid a vulnerability

- index.html
Takes an initial stab at including demos in the home page - on a small screen this is just a block of 5 videos, on a larger screen it gives some carousel behavior... Note: It's kind of yummier in chromium atm with the scroll-snapping, but for now so that I don't burn too much time before we review the basic ideas/etc... 
It's also adding a 'lite' custom element (that is, if we were going to actively maintain a dom to live changes, etc this would need more) for embedding the youtube videos easily while still being performant (basically, it creates an iframe with a srcdoc containing the poster image and a link that will load the full video in the frame only if you actually click it) to keep the page load demands fast/light.
----
Site preview: https://igalia.github.io/wpewebkit.org/demos/
> add intial stab at demos

- index.html
Variant on @meyerweb recent PR - it just... adopts/adapts the old and suggested @meyerweb use of the actual youtube library/api as follows:
* continues to use a lightweight placeholder rather than load the videos, cutting over 11mb (and more if we add videos) from the initial load... Note: this required adapting the CSS and I'm not sure I did great.
* switches from shadow dom to light dom so the API can work (lib uses document.getElementById, apparently), _but_ retains the original element similarly so you can continue to reason about the DOM in a fairly straightforward way (enhanced, not replaced)
* Lazily initializes the actual video on first interaction and initiates play (need to check this on iphone as I am not sure if that counts by their interaction/scripting criteria)
* loops and …
> tweak video carousel

- about/a-good-choice.md
- about/architecture.md
- about/builds.md
- about/exploring.md
- code.md
- index.html
- release/schedule/index.md
Did an editorial pass over all the public copy for clarity.  /about/architecture.html probably needs a review for technical accuracy; the rest of the pages were just touch-ups and should be fine.
----
Site preview: https://igalia.github.io/wpewebkit.org/doc-editorial/
> Editorial fixes

- release/schedule/index.md
Add a row to the versions compatibility table for the 2.32.x release series, due by the end of March 2021.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-compat-table/
> Update compat table for the upcoming 2.32.x release

- about/supported-hardware.md
This brings in a few small edits:
* List i.MX53 as supported.
* List i.MX6 as supported with the RDK backend.
* Remove redundant `USE_BACKEND_` prefix from RDK backend options.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezd/hw-compat/
> Add some improvements to the hardware compatibility tables

- _includes/post.html
This is a first pass at adding schema.org Microdata markup to pages which use the `post` template. This adds inline metadata to the HTML markup which helps e.g. crawlers have a better view of content.
An introduction to Microdata can be found here: https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/microdata/
> Add microdata markup for posts

- about/faq.md
Rewording the entry in the FAQ about Wayland usage in WPE was suggested [in the chat room](https://matrix.to/#/!TnYGzkMHApHVFiCOBX:matrix.org/$1Y3b8PXPzw01BckaMUIvmYPq7T1l7tTG4RFve_mn_-k?via=igalia.com&via=matrix.org)—so I did. Hopefully this makes things clearer.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/faq-improve/
> faq: Improve explanation about Wayland usage

- about/faq.md
Those are used for autoplugging and as last resort fallback, so make it clear that they are needed at runtime.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/faq-gstelements-crash/
> FAQ: Clarify that autoaudiosink and alsasink are needed

- about/exploring.md
WPE is officially available in some distros (unfortunately [not Fedora yet](https://bugzilla.redhat.com/show_bug.cgi?id=1601186)) so for some users that's one of the easiest ways to give it a try.
The text is very simple, the only odd thing about this change is that due to the page style hovering the "Install it from your distribution" text changes the cursor to a hand even though in this case it is not a link.
----
Site preview: https://igalia.github.io/wpewebkit.org/bertogg-distro-wpe-packages/
> Explain that you can install WPE from the distro

- about/supported-hardware.md
While the drm Cog shell should work as well, I do not have any first hand report about it, so I would rather leave it out of the table for now.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/hw-panfrost/
> hw: List fdo/fdo as backend/shell for Panfrost

- release/schedule/index.md
As per https://github.com/Igalia/meta-webkit/pull/282#issuecomment-862487940
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/compat-table/
> List WPEBackend-fdo 1.10 as compatible with WebKit 2.30

- .github/workflows/deploy.yml
- .github/workflows/pr.yml
- package-lock.json
- package.json
Update to the latest version of Eleventy, which is mainly a maintenance release which mostly pulls in updated dependencies. The release notes do not list any breaking change, and indeed the built site seems to be all fine.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/bump-11ty/
> Update to Eleventy 0.12.1

- about/faq.md
Update the date about the WebRTC status, add link to tracking bug for the GstWebRTC backend work.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/faq-gstrtc-update/
> faq: Update status of the GstWebRTC backend

- .github/workflows/pr.yml
Check pr.body before using it; when the body of the PR description is empty, GitHub sets the attribute to null.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/ci-no-body-in-pr/
> CI: Do not error on empty PR bodies

- _posts/2022-04-21-blog-happy-birthday-wpe.md
- _posts/2022-07-01-blog-overview-of-wpe.md
- _posts/2022-07-15-blog-wpe-graphics-architecture.md
- _posts/2022-07-28-blog-wpe-qa-tooling.md
Applies the following changes:
- Use `{{ '/some/path' | url }}` to generate links, which makes Eleventy generate valid links regardless of the path prefix and host name used during content generation (which makes previews work) and ensures the output always contains full URLs (good for consumption of content by feed readers.) This is applied to images as well.
- Avoid overlinking to ourselves, search engines have recognized such practices as an intention of artificially altering search results and will downrank pages using such practices.
- Made a few style edits here and there (e.g. “Cairo” is a proper name of the project so it goes with a capital letter, reformatted paragraphs to make them more legible in a text editor, and so on.)
- Make all images from articles centered.
----
Site …
> Cleanup blog post Markdown sources

- .eleventy.js
- release/verify/index.md
Make Eveventy copy PGP `.key` files to the output directory as-is, and ensure that the links are valid by using the `url` filter.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/fix-keyfile-copy/
> Arrange for copying PGP key files, fix links

- release/schedule/index.md
cog 0.16.x is stable and at least I'm using it sucessfully with wpewebkit 2.38.x, so update the compatibility table accordingly.
> Update cog compatibility for WebKit 2.38.x

- _includes/footer.html
The link also includes `rel="me"`, which can be used for cross-validating that we are who we claim to be in the fediverse.
This is related to #130 
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/fedi/
> Add Mastodon link in the page footer

- about/rpi-yocto-wpe.md
When discussing in a meeting, the reference to bmaptool was deemed confusing without providing links to bmap files, at which point everything start to be less flexible and more messy.
Also add instructions for flashing the rpi-64 image, the flashing instructions were meant to be generic but since we're using a specific image name, and we only have 2 in total anyway, make it convenient for all the devices.
----
Site preview: https://igalia.github.io/wpewebkit.org/manuelafm-patch-1/
> rpi-yocto: remove reference to bmaptool, add dd instr for rpi4-64

- about/faq.md
The BoringSSL bits were incorrect. Also update potential release year (wishful thinking).
----
Site preview: https://igalia.github.io/wpewebkit.org/faq-update/
> faq: Update WebRTC answer

- release/verify/index.md
The current link to @carlosgcampos' key is broken, so make the link point to the correct file.
On a different note: Since the redesign (#123), I can't find a link to https://wpewebkit.org/release/verify/ anymore. Is this on purpose?
> Fix link to Carlos García Campos' key

- .github/workflows/deploy.yml
- .github/workflows/pr.yml
Update to newer versions of the actions used by the CI workflows, in order to avoid warnings due to using Node older than version 16. While at it, remove uses of `actions/cache` in favor of the `cache: 'npm'` parameter to the `setup-node` action.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-gha/
> CI: Bump to versions of actions that use Node 16

- .github/workflows/pr.yml
According to https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ using `pull_request_target` will use the base branch instead of the fork branch. The base branch is considered trusted, and the automatic token handed over to GHA will include write permission.
Fixes #153
> CI: Give actions write permission to page contents

- .eleventy.js
- _authors/aperez.html
- _data/menu.js
- _includes/download-card.html
- _includes/footer.html
- _includes/head.html
- _includes/header.html
- _includes/post.html
- _includes/resources.html
- _posts/2022-04-21-blog-happy-birthday-wpe.md
- _posts/2022-07-01-blog-overview-of-wpe.md
- _posts/2022-07-15-blog-wpe-graphics-architecture.md
- _posts/2022-07-28-blog-wpe-qa-tooling.md
- _posts/2022-10-success-metrological.md
- _posts/2023-01-19-blog-new-svg-engine.md
- _posts/blog-06-integrating-wpe.md
- about/a-good-choice.md
- about/architecture.md
- about/builds.md
- about/explore-wpe.md
- about/index.md
- about/supported-hardware.md
- blog.md
- code.md
- developers/index.md
- index.html
- package-lock.json
- package.json
- release/verify/index.md
- security.md
Version 2 has been released a while ago, comes with speed improvements, and is lighter on dependencies. What's not to like? From a review of the release notes [1] it looks like there is no need to take care for any of the breaking changes, and the upgrade helper plug-in [2] passed with flying colors.
The update enables the new HTMLBase plugin included with Eleventy 2.0, which allows getting rid of virtually all the uses of the `url` filter when referring to site-local resources. This simplifies content authoring and is less error prone than the previous approach. Note that a few instances needed to be replaced with the `htmlBaseUrl` filter included with the plugin.
[1] https://www.11ty.dev/blog/eleventy-v2/
[2] https://github.com/11ty/eleventy-upgrade-help
----
Site preview: …
> 11ty: Upgrade to version 2.0 🎉

- about/a-good-choice.md
- about/architecture.md
- about/builds.md
- about/explore-wpe.md
- about/faq.md
- about/index.md
- about/supported-hardware.md
- about/what-is-embedded.md
- blog.md
- code.md
- developers/index.md
- index.html
- release.md
- release/schedule/index.md
- release/verify/index.md
- robots.liquid
- security.md
- sitemap.liquid
These are good to have, and an initial step towards having some kind of site map. At some point later on we would want to also have an HTML site map that is user-visible (instead of machine-readable like this), but that is left for a future PR.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/xmlsitemap-and-robotstxt/
> Add XML sitemap and robots.txt for web crawlers

- .eleventy.js
- package-lock.json
- package.json
Use the Eleventy syntax highlight plug-in instead of using the Markdown-it one directly, as it is expected to integrate better as it is an official plug-in [1]. It supports a few extra goodies (template filters, diff highlight), plus can be used in non-Markdown pages, if needed.
[1] https://www.11ty.dev/docs/plugins/syntaxhighlight/
----
Note that the output remain unchanged: both the previous approach use the Prism library, and this PR keeps the same CSS style for syntax highlighting. This is basically an “under the hood” change now that Eleventy 2.0 has such a plug-in 😺 
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/11ty-synhilite-plugin/
> 11ty: Prefer Eleventy's syntax highlight plug-in

- blog.md
- blog/2022-04-21-blog-happy-birthday-wpe.md
- blog/2022-07-01-blog-overview-of-wpe.md
- blog/2022-07-15-blog-wpe-graphics-architecture.md
- blog/2022-07-28-blog-wpe-qa-tooling.md
- blog/2022-09-29-blog-wpe-networking-overview.md
- blog/2022-10-success-metrological.md
- blog/2023-01-19-blog-new-svg-engine.md
- blog/blog-06-integrating-wpe.md
- blog/blog.json
- css/v2.css
This contains two changes:
- The first commit moves the blog content into the `blog/` subdirectory, for the sake of easiness of maintenance (we may want to do the same for releases and WSAs at some point).
- The second commit adds pagination to the blog section, with a pagination navigation widget, and the corresponding CSS rules.
The CSS styling is quite minimal, and probably could be done better, but we can iterate on that on follow-up patches. If there are any suggestions for the styling that would be quick to include in this PR, please let me know.
The page navigation looks like this:
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/paginate-blog/
> blog: Move posts into their own subdirectory, add pagination 

- css/v2.css
The `ul` inside the sticky nav was covering the whole width of the content, which was making the underlying hyperlinks and text unreachable for the mouse:
Setting the width of `ul` to `max-content` limits its size, and thus solves the issue.
----
Site preview: https://igalia.github.io/wpewebkit.org/sticky-nav-fix/
> Fix width of sticky nav on about page (and subpages)

- about/index.md
While fiddling in the DevTools for #165, I also noticed these errors in the console:
```
GET https://wpewebkit.org/img.youtube.com/vi/bg6yCx7VdPY/hqdefault.jpg    [HTTP/1.1 404 Not Found 169ms]
GET https://wpewebkit.org/img.youtube.com/vi/Nz2Y8HGdZDE/hqdefault.jpg    [HTTP/1.1 404 Not Found 487ms]
GET https://wpewebkit.org/img.youtube.com/vi/0L8Fv7sswSk/hqdefault.jpg    [HTTP/1.1 404 Not Found 490ms]
GET https://wpewebkit.org/img.youtube.com/vi/QNZJYOuVGiE/hqdefault.jpg    [HTTP/1.1 404 Not Found 481ms]
GET https://wpewebkit.org/img.youtube.com/vi/_X_23cb8l6o/hqdefault.jpg    [HTTP/1.1 404 Not Found 319ms]
```
Turned out that these links for video thumbnails (and the video URLs too) in the HTML markup are missing a slash after `https:/`. This PR fixes that.
(The thumbnails _do_ get …
> Fix links of YouTube videos and thumbnails (under "See WPE In Action...")

- release/2023-04-19-wpewebkit-2.40.1-released.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/manuelafm-patch-1/
> Fix typo in 2023-04-19-wpewebkit-2.40.1-released.md

- _includes/post.html
This Pr fixes spacing between date and download button in release pages - #150
> fixing spacing between date and download button in release pages 

- .eleventy.js
- _includes/header.html
In the global navigation, the `currentPage` class is applied to a link if the link's URL matches `page.url | topLevel`. This `topLevel` filter was excluding the trailing slash, resulting in no nav item getting the `currentPage` class (except `/`). Tweaking the regex in the `topLevel` filter fixes this.
The `ul` in the global navigation was also generating a class name based on the `topLevel` filter, so changed its `replace_first` filter to `replace` to accommodate accordingly.
(Also, I noticed that the link for the "Getting Started" page in the global navigation would never receive the `currentPage` class because its URL matches with `/about/`. Thus, when clicking on "Getting Started", the dashed line (indicating the current page) appears under "About" instead of "Getting Started", which …
> Fix regex in `topLevel` filter to match global nav links

- _includes/head.html
- blog.md
Remove the ugly link at the bottom of the blog and add syndication metadata to the header so that it's available in every page instead.
Fixes #174 
----
Site preview: https://igalia.github.io/wpewebkit.org/csaavedra/blog-feed-link/
> [blog] Remove the dangling Feed link and use link rel instead

- _includes/header.html
- css/v2.css
Closes #188
This does cause the button to not look like a button on the Get Started page, but like all the other links.  This was forced by the existing CSS, and may be desirable anyway, since it keeps the Call-To-Action button from looking like a Call To Action on the page it’s trying to get you to visit.  If it must continue to look like a button, even on its own page, significant rewriting of the template script and CSS will probably be needed.
----
Site preview: https://igalia.github.io/wpewebkit.org/issue-188/
> Hacked a way to link dashed line to Get Started

- _includes/header.html
Closes #188
This is basically the fix implemented in [1], which was rendered useless after PR #189 [2] got merged, so this is a quick fix.
[1] https://github.com/Igalia/wpewebkit.org/pull/191
[2] https://github.com/Igalia/wpewebkit.org/pull/189
Site preview: https://igalia.github.io/wpewebkit.org/issue-188-v2
> Fix the dashed line again (but for Get WPE now)

- index.html
We've had an open problem for some time that we'd like to highlight more in the main page, and the suggestion was to add a carousel with success stories or use cases.  For whatever reason we currently have 2 issues: First, we only have 2 approved entries. Carousels are already usually not a great choice for a bunch of reasons, but a carousel with only 2 things in it just seems weird, to be honest.  The other issue is that carousels should really contain "like" things and these are not - one is a use case and the other is a success story. So, there's been a PR for some time at #168 but it isn't deploying and also makes a specific choice there.
I just wanted to offer a very very simple alternative: Let's literally just put two things in that section until we get at least a third?
----
Site …
> Alternative use case/success story resolution

- .github/workflows/pr.yml
it seems that this is currently building a > 2gb artifact as it just keeps growing, and what's happening is a fail to upload (or at least that is happening, maybe there's more too though) because that exceeds the limit for GH... I'd like to let it clean so we can verify if this is the whole issue, we can go back to true after. We'd need to rerun any existing prs.
I guess this is #47 basically, but I never noticed that one until today
----
Site preview: https://igalia.github.io/wpewebkit.org/bkardell-patch-3/
> Clean / Update pr.yml

- about/index.md
- developers/index.md
We add the links from Developers only for now, will then work on a more elaborated page for documentation that will cover also cog, libwpe and the FDO backend, but for now this should be good enough.
----
Site preview: https://igalia.github.io/wpewebkit.org/api-docs/
> Add links to API documentation from "Developers" and "Learn & Discover"

- developers/index.md
Move the "(deprecated)" out of the actual link.
----
Site preview: https://igalia.github.io/wpewebkit.org/api-docs/
> Small cosmetic fix to the links to API documentation

- about/supported-hardware.md
It has been a while since Cog has renamed “shells” to “platform plug-ins” and the “fdo” one to “wl”, so carry on the change to the hardware compatibility page.
While at it, avoid the column width sizing CSS rules, which caused the last columns to be too narrow for their contents.
----
Site preview: https://igalia.github.io/wpewebkit.org/hw-update-cog-shells/
> Use current Cog platform plug-in names in supported HW table

- release/verify/index.md
The page at `/release/verify` was being skipped because it inherited the `skipHtmlSitemap` attribute from `release/release.json`. Override it in the page source to bring it back into the HTML site map page.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/relverify-htmlsitemap/
> Include /release/verify into HTML site map

- developers/index.md
Add a link to `/reference`, which contains the API documentation for releases that have it available, one subdirectory per version.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/developers-doc-link/
> developers: Link to the general documentation location

- _data/site.json
- _includes/post.html
- css/v2.css
- package-lock.json
- package.json
- release/release.11tydata.js
- release/release.json
Add a button to the documentation directory under `/reference` for those releases that have it. A small JS data script adds a `hasDocumentation` computed data property to each page, which will be true in release pages for the `wpewebkit` package, from versions `2.23.90` onwards (inclusive). The version comparison is done reusing the `semver` package. Just in case there might be some release after that version that does not have documentation, the `hideDocumentation` data attribute is also honored.
While at it, fix the post date being close tight to the download and documentation buttons. Instead, promote the `<time>` element containing the date to a block, which causes it to occupy its own “line”. To avoid stealing much vertical space for the buttons, a new `.btn-l` CSS class is added, …
> Add link to documentation directory in each release page

- about/faq.md
Add a new entry at the top of the FAQ to explicitly list the different licenses used for WPE, libwpe, WPEBackend-FDO and Cog, with links to the relevant copies of such licenses.
----
Site preview: https://igalia.github.io/wpewebkit.org/mention-oss-licenses/
> Add a explicit mention to the licenses used by WPE and its components

- about/faq.md
1. The libwebrtc backend now supports hardware-accelerated decoding, but not encoding.
2. Update outdated ETA for enabling GstWebRTC upstream by default.
----
Site preview: https://igalia.github.io/wpewebkit.org/update-webrtc-faq/
> Update FAQ about WebRTC

- .eleventy.js
- _includes/head.html
- security.njk
While at it, improve the titles of the feed links from the page head.
Fixes #185
----
Site preview: https://igalia.github.io/wpewebkit.org/wsa-security-feed/
> Add a new RSS feed for security advisories

- .eleventy.js
- _data/menu.js
- index.html
- package-lock.json
- package.json
- release.md
- release/release.11tydata.js
The main changes are that ESM modules are now supported, so on top of switching the syntax for imports/exports, `package` is now a keyword and some of their uses needed to be changed in the configuration file, and the `baseHtmlUrl` filter is now named `htmlBaseUrl`.
While at it, the uneeded `arrayLength` filter was removed, in favor of using `.length` directly on arrays. Also the unused `recentReleaseNotes` collection was removed.
----
Site preview: https://igalia.github.io/wpewebkit.org/update-11ty/
> npm: Update to Eleventy 3.x

- index.html
Fixes #249
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/remove-dupe-developers-section/
> Remove duplicate "Developers" section in front page

- index.html
Temporarily disable this drop-shadow, it breaks on Chromium-based browsers on Linux in some cases when GPU acceleration is enabled, causing artifacts like this:
Canary builds of Chromium seem to work better now, but there are still some artifacts when text is being selected, so let's remove this for now.
----
Site preview: https://igalia.github.io/wpewebkit.org/dropshadow/
> Disable the drop-shadow effect for header.page div > *

- blog.md
Using mathematical operations inside `{{ expression }}` does not work in all versions of the Liquid template engine, specially with newer versions as the templating engine attempts to improve compatibility with the original implementation. Instead of `+ 1`, use the `plus:` filter to adjust the page number of blog pagination permalinks, and quote the value in the front matter to avoid the YAML parser choking up on the colon.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/fix-pagination-permalink/
> blog: Fix pagination permalink expression

- blog/2025-04-success-glancr.md
A "TBD" was overlooked during the original PR.
> Add a preview message to the post on Glancr's success story

- developers/index.md
- wpt-status/index.html
This adds a new web-page to the site available at `/wpt-status` that renders a table showing the level support that WPE has for different Web specifications.
The json files with the data to show this are fetched from the server at [wpewebkit.org/wptreport-distilled-data](https://wpewebkit.org/wptreport-distilled-data) which will be automatically updated with the results of the WPE runs at [wpt.fyi](https://wpt.fyi)
```
Co-authored-by: Eric A. Meyer <eric@meyerweb.com>
Based-on-patch-by: Enrique Ocaña González <eocanha@igalia.com>
Tested-by: Brian Kardell <bkardell@gmail.com>
Signed-off-by: Carlos Alberto Lopez Perez <clopez@igalia.com>
```
----
~Site preview: https://igalia.github.io/wpewebkit.org/pr_add_wpt_status_dashboard/~
Site preview: …
> Add a new page with a "WPE Specification Support" dashboard.

- wpt-status/index.html
This replaces the link in the header (next to the version selector dropdown), which previously pointed to the GitHub WPT commit used for the run. In reality, that link isn't very interesting, since it just points to a random WPT commit where the run happened.
Instead, we now link to the corresponding results page on wpt.fyi, which makes it easier to view the actual detailed test output and seems more useful than opening a random commit on the WPT repository.
The GitHub WPT commit can still be accessed easily from the wpt.fyi results page by clicking on the WPT version label (with the small GitHub icon), so it still remains easily accessible.
> wpt-status: replace the header link to github/wpt with one to the wpt.fyi results

- developers/index.md
- wpt-status/index.html
Browser Compatibility Data (BCD) test results show a very detailed list of supported Web APIs, JavaScript features and CSS properties that can be useful for Web developers looking if they can use a specific feature in a given WPE version.
This patch reworks the `WPE Specification Support` webpage to offer this second source of data as an alternative view. It also renames the page to `WPE Web Support Status` in order to make the title better suited for a tool that includes both the BCD and WPT data.
On top of that it adds a few extra features to the web-page:
- Generate and use URL query params, that way is possible to share links that open a specific view.
- Cache the json data so it doesn't re-download the jsons each time a different version or view is selected.
- Add a search/filter …
> wpt-status: Add an alternative view based on results from BCD tests.
