Igalia/wpewebkit.org

- _posts/2019-04-10-security-advisory-2019-0002.md
> WSA-2019-0002

- index.html
Also change a normal dash to an `&mdash;` :wink:
> index: Fix typo embdedded -> embedded

- about/supported-hardware.md
> supported-hardware: Complement informations

- about/code.md
> Prefer Markdown link syntax where possible

- index.html
----
Site preview: https://igalia.github.io/wpewebkit.org/philn-patch-2/
> index: Fix a couple typos

- _includes/header.html
- code.md
Fixes #29
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/change-code-path/
> Move "Code" page URL path to be just /code/

- .eleventy.js
- .github/workflows/pr.yml
- _data/site.json
- _includes/default.html
- _includes/head.html
- _includes/page.html
- index.html
Fixes #39
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/opengraph/
> head: Add OpenGraph and Twitter card metadata

- package-lock.json
- package.json
SSIA.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/misc-npm-updates/
> package.json: Update markdown-it-anchor to version 6

- package-lock.json
- package.json
SSIA
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/misc-npm-updates/
> npm: Update Eleventy to v0.11.1

- _includes/header.html
- about/architecture.md
- index.html
----
Site preview: https://igalia.github.io/wpewebkit.org/arch-doc/
----
Site preview: https://igalia.github.io/wpewebkit.org/arch-doc/
> Basic architecture docs

- index.html
----
Site preview: https://igalia.github.io/wpewebkit.org/issue52/
> Removed drop shadows from home page carousel buttons

- _includes/header.html
- about/faq.md
- css/stylish-portfolio.css
Fixes #26
----
Site preview: https://igalia.github.io/wpewebkit.org/faq/
> about: Add FAQ page

- about/faq.md
----
Site preview: https://igalia.github.io/wpewebkit.org/faq-hw-os/
> faq: Add questions about supported hardware and OS

- about/faq.md
Please review the changes for accuracy.  Thank you!
----
Site preview: https://igalia.github.io/wpewebkit.org/issue-69/
> WIP: Copy edits to the FAQ

- about/supported-hardware.md
Just a little cleanup, really.  Not sure I love the TOC but I don’t have a different idea, so leaving as-is for now.  Please review!
----
Site preview: https://igalia.github.io/wpewebkit.org/issue-71/
> Restyled tables, tweaked column headers

- about/faq.md
I hit this issue myself today, and once I figured out it turned out that I had solved it a couple of times before. As I keep hitting the same stone, it seemed like a good idea to add this entry to the FAQ.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/more-faqs/
> faq: Add entry about shared-mime-info

- about/faq.md
Thanks @bertogg for spotting a word that does not belong in a phrase, and for pointing out that being clearer never hurts 😄 
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/faq-improve/
> FAQ: Clarify Wayland usage further, fix typo

- _includes/footer.html
- code.md
SSIA.
For some background behind the move, one could start here: https://www.kline.sh
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update-irc/
> Change IRC contact info from Freenode to OFTC

- package-lock.json
- package.json
SSIA.
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/update11ty/
> Update Eleventy to version 0.12

- .eleventy.js
- _includes/head.html
- package-lock.json
- package.json
Let's upgrade to latest Eleventy - nice framework btw. I'm familiarizing myself with it, and this is a good opportunity to resolve 'npm audit' warnings.
> Update to latest 11ty 1.0.0

- about/exploring.md
.
----
Site preview: https://igalia.github.io/wpewebkit.org/philn-patch-2/
> exploring: Mention Fedora packages repository

- _authors/nzimmermann.html
- css/stylish-portfolio.css
null
----
Site preview: https://igalia.github.io/wpewebkit.org/nzimmermann/wpe_5th_anniversary_fixes/
> Fix author footer on small devices

- blog.md
- blog.njk
null
----
Site preview: https://igalia.github.io/wpewebkit.org/blog-feed/
> Add blog feed

- _authors/csaavedra.html
- _posts/2022-07-01-blog-overview-of-wpe.md
Also add a short bio page for myself
----
Site preview: https://igalia.github.io/wpewebkit.org/post-architecture-of-wpe/
> Add a post about the architecture of WPE to the blog

- about/a-good-choice.md
this is the only bullet that repeated WPE in the start, it seemed a slightly different voice.
Mainly though I want to see if I can get a preview from a PR on this branch :)
> Minor text tweak

- .eleventy.js
- _posts/2022-04-21-blog-happy-birthday-wpe.md
- _posts/2022-07-01-blog-overview-of-wpe.md
- _posts/2022-07-15-blog-wpe-graphics-architecture.md
- _posts/2022-07-28-blog-wpe-qa-tooling.md
- blog.md
Added image thumbnails and preview text to the main Blog page, along with some Gridification.  This did require adding some new metadata to blog posts, as Liquid appears too limited to pull that sort of information out natively.
----
Site preview: https://igalia.github.io/wpewebkit.org/blog/
> Splurged up the Blog portion of the site

- package-lock.json
Here's a periodic dependencies update 🙃 
----
Site preview: https://igalia.github.io/wpewebkit.org/aperezdc/bump-deps/
> 11ty: Update dependencies to latest versions

- README.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/bump/
> README edit to force rebuild (updates footer currentYear)

- developers/index.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/mafm-link-yocto/
> Add link to the new RaspberryPi images

- about/a-good-choice.md
- developers/index.md
- index.html
We will add a mention to Android as well at a later point.
----
Site preview: https://igalia.github.io/wpewebkit.org/linux-mention/
> Mention Linux as the base platform more clearly across the website

- about/explore-wpe.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/bkardell-patch-3/
> Fix broken contact link

- _posts/2023-11-15-security-advisory-2023-0010.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/mcatanzaro/CVE-2023-42852/
> Update attribution for CVE-2023-42852

- _includes/page.html
- index.html
null
----
Site preview: https://igalia.github.io/wpewebkit.org/survey-home/
> Banner on home page, better placement of banner on sub-pages

- blog/2023-01-success-digital-signage.md
- redirects.md
We are also changing the permalink so we need a redirect for it.
----
Site preview: https://igalia.github.io/wpewebkit.org/issues/208/
> Rename Digital Signage post as an "Use case" and add redirect

- index.html
- redirects.md
The previous attempt to fix this issue introduced a mistake in the redirect and forgot to update the links in the frontpage.
----
Site preview: https://igalia.github.io/wpewebkit.org/issues/208/
> Fix typo in the redirect + update link in the front page

- about/supported-hardware.md
SSIA.
----
Site preview: https://igalia.github.io/wpewebkit.org/imx6+gc880-supported/
> Add iMX6 + Vivante GC880 as supported

- about/get-wpe.md
SSIA.
----
Site preview: https://igalia.github.io/wpewebkit.org/buildinstructions-csdk/
> Change build instructions to mention the container SDK

- index.html
It's already  mentioned in "Get WPE" section, but this would be good too.
----
Site preview: https://igalia.github.io/wpewebkit.org/open-source-mention/
> Mention WPE's Open Source nature in the frontpage

- blog/2024-10-07-wpewebkit-2.46.md
This was co-authored with Adrián Pérez but I don't see a way to add co-authors to the blog.
----
Site preview: https://igalia.github.io/wpewebkit.org/2.46-release-notes/
> blog: add a post about the 2.46 release

- release/schedule/index.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/compat-table-2.46/
> Add compatibility table entry for WPE WebKit 2.46.x

- index.html
null
----
Site preview: https://igalia.github.io/wpewebkit.org/carousel-fix/
> carousel: Editorial fix for video and broadcasting section

- index.html
I'm sorry I missed this one in the previous PR.
----
Site preview: https://igalia.github.io/wpewebkit.org/philn-patch-2/
> carousel: Additional fixup in broadcasting section

- blog/2025-04-11-wpewebkit-2.48.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/2.48-highlights/
> blog: WPE WebKit 2.48 highlights

- developers/index.md
null
----
Site preview: https://igalia.github.io/wpewebkit.org/patch-1/
> Fix link to extension API 2.0
